name: "🐛 Report a Bug"
title: "[Bug] "
description: Submit an issue report to help us improve.
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I am using the latest version of Final Suspect.
          required: true
        - label: Final Suspect is incompatible with any other mods, and I confirm that I have not installed any other mods alongside Final Suspect.
          required: true
        - label: I have searched the [Issue list](https://github.com/Slok7565/FinalSuspect/issues) for related issues and still cannot resolve my problem, or this issue has never been reported before.
          required: true
        - label: I have read and agree to this project's [Contributor Code of Conduct](https://github.com/Slok7565/FinalSuspect/blob/FinalSus/CODE_OF_CONDUCT.md).
          required: true

  - type: textarea
    attributes:
      label: Problem Description
      description: What happened?
      placeholder: Clearly and specifically describe what happened or what problem you encountered.
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Client Type
      description: Before confirming the issue, we first need to know which client is being used.
      options:
      - Steam
      - Epic
      - Starlight Android
    validations:
      required: true

  - type: textarea
    attributes:
      label: How to Reproduce?
      description: Steps to reproduce the issue.
      placeholder: |
        For example:
        1. Open ...
        2. Click ...
        3. Issue reproduced
    validations:
      required: true

  - type: input
    attributes:
      label: Final Suspect Version
      description: The version of Final Suspect in which the issue occurred. Please do not use meaningless values such as `latest`.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error Logs
      description: Debug-level logs related to the issue. Issues without valid logs will be closed. Thank you for your understanding.
      render: text
    validations:
      required: true

  - type: upload
    attributes:
      label: Additional Information
      description: |
        Other supporting materials related to the issue, such as a reproduction video or the complete log file. Please upload images in the Problem Description section.<br>
        If your logs are too long to paste directly into the field above, you may paste only the key log entries there and upload the complete log file here.
    validations:
      accept: ".txt,.log,.mp4,.mov,.webm,.zip,.gz"

  - type: markdown
    attributes:
      value: "Finally, thank you for taking the time to report this issue!"
