name: "🎉 功能建议"
title: "[Feature] "
description: 向我们提交一个新的功能想法或建议。
labels: ["Considered"]
body:
  - type: checkboxes
    attributes:
      label: 检查清单
      options:
        - label: 我已在 [Issue 列表](https://github.com/Slok7565/FinalSuspect/issues)中搜索过相关功能，确认该功能想法从未被提出过。
          required: true
        - label: 我已阅读并同意本项目的[贡献者行为准则](https://github.com/Slok7565/FinalSuspect/blob/FinalSus/CODE_OF_CONDUCT.md)。
          required: true

  - type: textarea
    attributes:
      label: 功能描述
      placeholder: 详细描述您希望添加的功能。
    validations:
      required: true

  - type: textarea
    attributes:
      label: 使用场景
      placeholder: 描述您建议的功能的使用场景。

  - type: markdown
    attributes:
      value: "感谢您向我们提交您宝贵的想法！"